-- MySQL Script generated by MySQL Workbench
-- Thu Jan 28 19:40:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
                                             `id` INT NOT NULL AUTO_INCREMENT,
                                             `username` VARCHAR(255) NOT NULL,
                                             `password` VARCHAR(255) NOT NULL,
                                             `email` VARCHAR(255) NULL,
                                             `name` VARCHAR(127) NULL,
                                             `surname` VARCHAR(255) NULL,
                                             `create_date` TIMESTAMP NULL,
                                             PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`book` (
                                             `id` INT NOT NULL AUTO_INCREMENT,
                                             `name` VARCHAR(255) NULL,
                                             `author` VARCHAR(255) NULL,
                                             PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_read_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_read_book` (
                                                       `user_id` INT NOT NULL,
                                                       `book_id` INT NOT NULL,
                                                       PRIMARY KEY (`user_id`, `book_id`),
                                                       INDEX `fk_user_has_book_book1_idx` (`book_id` ASC) VISIBLE,
                                                       INDEX `fk_user_has_book_user_idx` (`user_id` ASC) VISIBLE,
                                                       CONSTRAINT `fk_user_has_book_user`
                                                           FOREIGN KEY (`user_id`)
                                                               REFERENCES `mydb`.`user` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION,
                                                       CONSTRAINT `fk_user_has_book_book1`
                                                           FOREIGN KEY (`book_id`)
                                                               REFERENCES `mydb`.`book` (`id`)
                                                               ON DELETE NO ACTION
                                                               ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
                                             `id` INT NOT NULL AUTO_INCREMENT,
                                             `name` VARCHAR(255) NOT NULL,
                                             PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_role` (
                                                      `user_id` INT NOT NULL,
                                                      `role_id` INT NOT NULL,
                                                      PRIMARY KEY (`user_id`, `role_id`),
                                                      INDEX `fk_user_has_role_role1_idx` (`role_id` ASC) VISIBLE,
                                                      INDEX `fk_user_has_role_user1_idx` (`user_id` ASC) VISIBLE,
                                                      CONSTRAINT `fk_user_has_role_user1`
                                                          FOREIGN KEY (`user_id`)
                                                              REFERENCES `mydb`.`user` (`id`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION,
                                                      CONSTRAINT `fk_user_has_role_role1`
                                                          FOREIGN KEY (`role_id`)
                                                              REFERENCES `mydb`.`role` (`id`)
                                                              ON DELETE NO ACTION
                                                              ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
